[book]
authors = ["J. Simon Richard", "Fabio Hinojosa Jimenez", "Vishnu Kalavakuntala", "Mason Clay", "Charlie Strickland", "Meir Manevich"]
language = "en"
multilingual = false
src = "src"
title = "The CPT's Linux & Git Workshop"


[output.html.fold]
enable = true
level = 1
